openapi: 3.1.0
info:
  title: YOUR TITLE
  description: Airtable API for reading, writing, filtering, and updating household entries.
  version: 1.3.1
servers:
  - url: https://api.airtable.com/v0/YOUR-TABLE
    description: Airtable Base - YOUR - TABLE
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas: {}
security:
  - bearerAuth: []
paths:
  /Text%20Entries:
    get:
      operationId: getFilteredEntries
      summary: Get household entries with optional filters and pagination
      description: Retrieves records from the Text Entries table with optional filters for person, priority, category, date, and completion status.
      parameters:
        - name: maxRecords
          in: query
          schema:
            type: integer
            default: 100
            maximum: 100
            minimum: 1
        - name: offset
          in: query
          schema:
            type: string
        - name: person
          in: query
          schema:
            type: string
        - name: category
          in: query
          schema:
            type: string
        - name: priority
          in: query
          schema:
            type: string
        - name: since
          in: query
          schema:
            type: string
            format: date
        - name: completed
          in: query
          schema:
            type: boolean
        - name: sortField
          in: query
          schema:
            type: string
            default: Submitted At
        - name: sortDirection
          in: query
          schema:
            type: string
            enum: [asc, desc]
            default: desc
      responses:
        '200':
          description: A list of filtered entries.
          content:
            application/json:
              schema:
                type: object
                properties:
                  offset:
                    type: string
                  records:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        fields:
                          type: object
                          properties:
                            Person Submitting:
                              type: string
                            Submitted Text:
                              type: string
                            Submitted At:
                              type: string
                              format: date-time
                            Entry ID:
                              type: string
                            Category:
                              type: string
                            Priority:
                              type: string
                            Completed:
                              type: boolean
    post:
      operationId: createEntry
      summary: Create a new household entry
      description: Adds a new record to the Text Entries table.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fields:
                  type: object
                  required:
                    - Person Submitting
                    - Submitted Text
                  properties:
                    Person Submitting:
                      type: string
                    Submitted Text:
                      type: string
                    Submitted At:
                      type: string
                      format: date-time
                    Category:
                      type: string
                      description: Optional. Default to "Tasks" if not provided.
                    Priority:
                      type: string
                      description: Optional. Leave blank if not provided.
                    Completed:
                      type: boolean
                      default: false
      responses:
        '200':
          description: Entry created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  fields:
                    type: object

  /Text%20Entries/{recordId}:
    patch:
      operationId: markEntryCompleted
      summary: Mark an entry as completed
      description: Updates a record in the Text Entries table to set Completed = true.
      parameters:
        - name: recordId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fields:
                  type: object
                  properties:
                    Completed:
                      type: boolean
                      example: true
      responses:
        '200':
          description: Record successfully updated.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  fields:
                    type: object
